### ISSUE TITLE
CFITSIO error in nifpmsel

### ISSUE THREAD

**Issue by nlewand** [paulray/NICERsoft#99]
When running psrpipe.py the nifpmsel step fails. 

```
Task nifpmsel 1.8 terminating with status -1
Traceback (most recent call last):
  File "/scratch/software/nicer_20230814/NICERsoft/scripts/psrpipe.py", line 653, in <module>
    runcmd(cmd)
  File "/scratch/software/nicer_20230814/NICERsoft/scripts/psrpipe.py", line 256, in runcmd
    check_call(cmd, env=os.environ)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nifpmsel', 'infile=2070020493_pipe/intermediate.evt', 'outfile=2070020493_pipe/cleanfilt.evt', 'detlist=launch', 'mkfile=2070020493/auxil/ni2070020493.mkf', 'clobber=yes', 'history=yes']' returned non-zero exit status 255.
```

Rerunning this command by hand shows the following error:

```
nifpmsel infile=2070020493_pipe/intermediate.evt outfile=2070020493_pipe/cleanfilt.evt detlist=launch mkfile=2070020493/auxil/ni2070020493.mkf clobber=yes history=yes
nifpmsel 1.8
  FPM List: launch
  Recalculating GTIs
ERROR: (internal error)  GTI is missing extension name at /scratch/software/nicer_20230814/heasoft-6.32/x86_64-pc-linux-gnu-libc2.36/bin/nifpmsel line 966.
Dumping CFITSIO error stack:
--------------------------------------------------
Extension doesn't start with SIMPLE or XTENSION keyword. (ffrhdu)
END
Error while closing HDU number 0 (ffchdu).
--------------------------------------------------
CFITSIO error stack dump complete.
Task nifpmsel 1.8 terminating with status -1
```

**Comment by paulray** [comment]
Interesting. What source is this? I'd like to try to replicate the error.
also can you give the output of this command?
```ftlist 2070020493_pipe/intermediate.evt  HC```
